spring.application.name=mallapi

## view resolver api\uc11c\ubc84 \uc124\uc815\uc73c\ub85c \ubbf8\uc0ac\uc6a9\ud568
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
 
# oracle jdbc \uc124\uc815  
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=malldbuser
spring.datasource.password=malldbuser
 
# jpa \uc124\uc815
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#\uc624\ub77c\ud074\uc740 \uc2dc\ud000\uc2a4\ub97c \uc790\ub3d9\uc73c\ub85c \ub9cc\ub4e4\uc5b4\uc8fc\uc9c0 \uc54a\uc544\uc11c false
spring.jpa.properties.hibernate.id.new_generator_mappings=false
#\ud14c\uc774\ube14\uc740 \uceec\ub7fc\uc744 \uc0c8\ub85c \ucd94\uac00\ud558\uac70\ub098 \ud558\uc9c0 \uc54a\ub294 \uc774\uc0c1 \uc0c8\ub85c \ub9cc\ub4e4\uc9c0 \uc54a\uc744\uac70\ub2e4
spring.jpa.hibernate.ddl-auto=update
#sql\ubb38\uc744 \ud55c\uc904\ub85c \ub9cc\ub4e4\uac70\ub2e4
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true
#\ub85c\uadf8\ud30c\uc77c\uc5d0 sql\ubb38\uc744 \uae30\ub85d\ub0a8\uae30\uaca0\ub2e4.
spring.jpa.show-sql=true

##\ub85c\uadf8\ucd9c\ub825 \ubc94\uc704 \uc124\uc815
logging.level.org.hibernate=info
